import React from "react"

// considering writeup of entire project on web side, render latex with: https://www.npmjs.com/package/react-latex-next

export default function Home(){
    return(
        <div className="mt-2">
            <div className=" container">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at ipsum quis sem condimentum finibus. Proin pretium non lacus eu lacinia. In id elementum ipsum. Nam consequat faucibus arcu at sagittis. Donec vitae nisl a felis efficitur congue nec nec dui. Duis interdum nibh dui, vitae porttitor orci consectetur at. Maecenas posuere condimentum scelerisque. Quisque molestie molestie gravida. In hac habitasse platea dictumst. Etiam vel odio eget libero tempus feugiat. Donec semper justo nec nulla dapibus, et molestie est rutrum.
                    Quisque faucibus dui id erat elementum suscipit. Quisque ac eros mattis, vehicula nisl ut, aliquet urna. Sed dolor tellus, gravida id vehicula sed, sagittis ut urna. In hac habitasse platea dictumst. Duis viverra vulputate orci eu placerat. Morbi ligula nulla, dapibus volutpat mi non, faucibus gravida lacus. Ut faucibus vulputate eros, a aliquam purus ornare vel. Suspendisse massa lectus, facilisis ac pulvinar ac, hendrerit nec orci. Curabitur id nunc efficitur, convallis nisl a, finibus enim. Pellentesque dolor erat, tristique at tincidunt ac, mattis viverra ante. Donec fringilla eu justo eget iaculis. Integer vitae efficitur lorem. Nam blandit quam ligula, quis egestas lorem blandit eu. Suspendisse sed urna eget massa hendrerit accumsan.
                    Morbi quis eros luctus, porttitor ipsum nec, sollicitudin libero. Morbi a vulputate libero. Fusce convallis placerat nisl, a dictum nisl dapibus vel. Quisque quam dui, rhoncus et neque sed, cursus iaculis sapien. Pellentesque vitae nisi magna. In mi metus, lacinia tincidunt neque in, consectetur pretium nulla. Cras sem nulla, rhoncus ultrices pellentesque id, lacinia vel velit. Suspendisse convallis enim eu urna facilisis, a rutrum dolor fermentum. Curabitur et malesuada ex.
                    Sed leo felis, fringilla eget tortor finibus, vulputate pretium nibh. Sed diam nunc, fermentum nec ex sed, tempor hendrerit erat. Sed ultrices euismod magna vitae finibus. Nullam vulputate eu nulla in volutpat. Ut sit amet pretium nisl, nec egestas metus. Integer iaculis commodo libero, eu congue nunc imperdiet id. Aenean ultricies, ex vitae mattis eleifend, libero felis hendrerit ligula, non mattis arcu leo at purus. Vestibulum augue ante, sagittis ac sem in, egestas iaculis ex. Morbi ornare vel magna vel pulvinar. Nullam eget accumsan sapien. Cras placerat venenatis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum iaculis auctor risus in dictum. Curabitur non blandit enim. Nunc eu ligula nec purus scelerisque posuere at et quam. Maecenas vel ex et velit vulputate ultricies nec sed lectus. Aenean condimentum velit leo, maximus commodo tellus aliquam posuere. Donec tempus vulputate est quis porta. Donec aliquet, mauris porta accumsan pellentesque, ante nisi convallis tellus, in tincidunt neque sapien eu augue. Sed volutpat dui at lorem semper, non venenatis mauris rutrum. 
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at ipsum quis sem condimentum finibus. Proin pretium non lacus eu lacinia. In id elementum ipsum. Nam consequat faucibus arcu at sagittis. Donec vitae nisl a felis efficitur congue nec nec dui. Duis interdum nibh dui, vitae porttitor orci consectetur at. Maecenas posuere condimentum scelerisque. Quisque molestie molestie gravida. In hac habitasse platea dictumst. Etiam vel odio eget libero tempus feugiat. Donec semper justo nec nulla dapibus, et molestie est rutrum.
                    Quisque faucibus dui id erat elementum suscipit. Quisque ac eros mattis, vehicula nisl ut, aliquet urna. Sed dolor tellus, gravida id vehicula sed, sagittis ut urna. In hac habitasse platea dictumst. Duis viverra vulputate orci eu placerat. Morbi ligula nulla, dapibus volutpat mi non, faucibus gravida lacus. Ut faucibus vulputate eros, a aliquam purus ornare vel. Suspendisse massa lectus, facilisis ac pulvinar ac, hendrerit nec orci. Curabitur id nunc efficitur, convallis nisl a, finibus enim. Pellentesque dolor erat, tristique at tincidunt ac, mattis viverra ante. Donec fringilla eu justo eget iaculis. Integer vitae efficitur lorem. Nam blandit quam ligula, quis egestas lorem blandit eu. Suspendisse sed urna eget massa hendrerit accumsan.
                    Morbi quis eros luctus, porttitor ipsum nec, sollicitudin libero. Morbi a vulputate libero. Fusce convallis placerat nisl, a dictum nisl dapibus vel. Quisque quam dui, rhoncus et neque sed, cursus iaculis sapien. Pellentesque vitae nisi magna. In mi metus, lacinia tincidunt neque in, consectetur pretium nulla. Cras sem nulla, rhoncus ultrices pellentesque id, lacinia vel velit. Suspendisse convallis enim eu urna facilisis, a rutrum dolor fermentum. Curabitur et malesuada ex.
                    Sed leo felis, fringilla eget tortor finibus, vulputate pretium nibh. Sed diam nunc, fermentum nec ex sed, tempor hendrerit erat. Sed ultrices euismod magna vitae finibus. Nullam vulputate eu nulla in volutpat. Ut sit amet pretium nisl, nec egestas metus. Integer iaculis commodo libero, eu congue nunc imperdiet id. Aenean ultricies, ex vitae mattis eleifend, libero felis hendrerit ligula, non mattis arcu leo at purus. Vestibulum augue ante, sagittis ac sem in, egestas iaculis ex. Morbi ornare vel magna vel pulvinar. Nullam eget accumsan sapien. Cras placerat venenatis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum iaculis auctor risus in dictum. Curabitur non blandit enim. Nunc eu ligula nec purus scelerisque posuere at et quam. Maecenas vel ex et velit vulputate ultricies nec sed lectus. Aenean condimentum velit leo, maximus commodo tellus aliquam posuere. Donec tempus vulputate est quis porta. Donec aliquet, mauris porta accumsan pellentesque, ante nisi convallis tellus, in tincidunt neque sapien eu augue. Sed volutpat dui at lorem semper, non venenatis mauris rutrum. 
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at ipsum quis sem condimentum finibus. Proin pretium non lacus eu lacinia. In id elementum ipsum. Nam consequat faucibus arcu at sagittis. Donec vitae nisl a felis efficitur congue nec nec dui. Duis interdum nibh dui, vitae porttitor orci consectetur at. Maecenas posuere condimentum scelerisque. Quisque molestie molestie gravida. In hac habitasse platea dictumst. Etiam vel odio eget libero tempus feugiat. Donec semper justo nec nulla dapibus, et molestie est rutrum.
                    Quisque faucibus dui id erat elementum suscipit. Quisque ac eros mattis, vehicula nisl ut, aliquet urna. Sed dolor tellus, gravida id vehicula sed, sagittis ut urna. In hac habitasse platea dictumst. Duis viverra vulputate orci eu placerat. Morbi ligula nulla, dapibus volutpat mi non, faucibus gravida lacus. Ut faucibus vulputate eros, a aliquam purus ornare vel. Suspendisse massa lectus, facilisis ac pulvinar ac, hendrerit nec orci. Curabitur id nunc efficitur, convallis nisl a, finibus enim. Pellentesque dolor erat, tristique at tincidunt ac, mattis viverra ante. Donec fringilla eu justo eget iaculis. Integer vitae efficitur lorem. Nam blandit quam ligula, quis egestas lorem blandit eu. Suspendisse sed urna eget massa hendrerit accumsan.
                    Morbi quis eros luctus, porttitor ipsum nec, sollicitudin libero. Morbi a vulputate libero. Fusce convallis placerat nisl, a dictum nisl dapibus vel. Quisque quam dui, rhoncus et neque sed, cursus iaculis sapien. Pellentesque vitae nisi magna. In mi metus, lacinia tincidunt neque in, consectetur pretium nulla. Cras sem nulla, rhoncus ultrices pellentesque id, lacinia vel velit. Suspendisse convallis enim eu urna facilisis, a rutrum dolor fermentum. Curabitur et malesuada ex.
                    Sed leo felis, fringilla eget tortor finibus, vulputate pretium nibh. Sed diam nunc, fermentum nec ex sed, tempor hendrerit erat. Sed ultrices euismod magna vitae finibus. Nullam vulputate eu nulla in volutpat. Ut sit amet pretium nisl, nec egestas metus. Integer iaculis commodo libero, eu congue nunc imperdiet id. Aenean ultricies, ex vitae mattis eleifend, libero felis hendrerit ligula, non mattis arcu leo at purus. Vestibulum augue ante, sagittis ac sem in, egestas iaculis ex. Morbi ornare vel magna vel pulvinar. Nullam eget accumsan sapien. Cras placerat venenatis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum iaculis auctor risus in dictum. Curabitur non blandit enim. Nunc eu ligula nec purus scelerisque posuere at et quam. Maecenas vel ex et velit vulputate ultricies nec sed lectus. Aenean condimentum velit leo, maximus commodo tellus aliquam posuere. Donec tempus vulputate est quis porta. Donec aliquet, mauris porta accumsan pellentesque, ante nisi convallis tellus, in tincidunt neque sapien eu augue. Sed volutpat dui at lorem semper, non venenatis mauris rutrum. 
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at ipsum quis sem condimentum finibus. Proin pretium non lacus eu lacinia. In id elementum ipsum. Nam consequat faucibus arcu at sagittis. Donec vitae nisl a felis efficitur congue nec nec dui. Duis interdum nibh dui, vitae porttitor orci consectetur at. Maecenas posuere condimentum scelerisque. Quisque molestie molestie gravida. In hac habitasse platea dictumst. Etiam vel odio eget libero tempus feugiat. Donec semper justo nec nulla dapibus, et molestie est rutrum.
                    Quisque faucibus dui id erat elementum suscipit. Quisque ac eros mattis, vehicula nisl ut, aliquet urna. Sed dolor tellus, gravida id vehicula sed, sagittis ut urna. In hac habitasse platea dictumst. Duis viverra vulputate orci eu placerat. Morbi ligula nulla, dapibus volutpat mi non, faucibus gravida lacus. Ut faucibus vulputate eros, a aliquam purus ornare vel. Suspendisse massa lectus, facilisis ac pulvinar ac, hendrerit nec orci. Curabitur id nunc efficitur, convallis nisl a, finibus enim. Pellentesque dolor erat, tristique at tincidunt ac, mattis viverra ante. Donec fringilla eu justo eget iaculis. Integer vitae efficitur lorem. Nam blandit quam ligula, quis egestas lorem blandit eu. Suspendisse sed urna eget massa hendrerit accumsan.
                    Morbi quis eros luctus, porttitor ipsum nec, sollicitudin libero. Morbi a vulputate libero. Fusce convallis placerat nisl, a dictum nisl dapibus vel. Quisque quam dui, rhoncus et neque sed, cursus iaculis sapien. Pellentesque vitae nisi magna. In mi metus, lacinia tincidunt neque in, consectetur pretium nulla. Cras sem nulla, rhoncus ultrices pellentesque id, lacinia vel velit. Suspendisse convallis enim eu urna facilisis, a rutrum dolor fermentum. Curabitur et malesuada ex.
                    Sed leo felis, fringilla eget tortor finibus, vulputate pretium nibh. Sed diam nunc, fermentum nec ex sed, tempor hendrerit erat. Sed ultrices euismod magna vitae finibus. Nullam vulputate eu nulla in volutpat. Ut sit amet pretium nisl, nec egestas metus. Integer iaculis commodo libero, eu congue nunc imperdiet id. Aenean ultricies, ex vitae mattis eleifend, libero felis hendrerit ligula, non mattis arcu leo at purus. Vestibulum augue ante, sagittis ac sem in, egestas iaculis ex. Morbi ornare vel magna vel pulvinar. Nullam eget accumsan sapien. Cras placerat venenatis tempus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum iaculis auctor risus in dictum. Curabitur non blandit enim. Nunc eu ligula nec purus scelerisque posuere at et quam. Maecenas vel ex et velit vulputate ultricies nec sed lectus. Aenean condimentum velit leo, maximus commodo tellus aliquam posuere. Donec tempus vulputate est quis porta. Donec aliquet, mauris porta accumsan pellentesque, ante nisi convallis tellus, in tincidunt neque sapien eu augue. Sed volutpat dui at lorem semper, non venenatis mauris rutrum. 
                </p>
            </div>
        </div>
    )
}